defaults:
  - orchestrators/eda
  - orchestrators/pipelines
  - orchestrators/report

project:
  name: demo_project
  random_state: 42
  output_dir: outputs

logger:
  backend: structlog        # "stdlib" ou "structlog"
  app_name: mlp
  level: INFO               # DEBUG/INFO/WARNING/ERROR/CRITICAL
  json_mode: false          # true en prod pour JSON
  file_path: null           # ex: logs/mlp.log
  file_max_bytes: 5242880
  file_backup_count: 3
  uvicorn_noise_filter: true
  default_fields:
    app: mlp
    env: dev

mlflow:
  enabled: true
  experiment: mlp-experiments
