name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: Ruff (lint)
        run: ruff check --output-format=github
      - name: Ruff (format check)
        run: ruff format --diff
      - name: Mypy
        run: mypy src
      - name: Pytest
        run: pytest
